let config = {
	"user":"usr-dark-path",
	"server":"localhost",
	"instantMessages":false,
	"rootModeEnabled":false,
	"correctRootPassword":"P@ssw0rd007",
	"sshAddresss":"11.203.25.105",
	"rootPasswordAttempts":0,
	"playlistLink":"https://open.spotify.com/user/1296024381/playlist/7tRV4WDhqAV9V2Mdz9BMXf?si=iUkuqqMAT4GCzvZ148l35w",
	"repoLink":"https://github.com/DejayJD/a-dark-path",
	"cluesRemaining":3,
	"AESPassword":"yeugh",
	"AESHash":"JgMmKNa5EVtIWfSQ9ZUFO8l1CE",
	"githashlink":"e1fcea361f4e67178de6663a9248c46e458cb900",
	"paperclipsMined":0,
	"currentMiningCycle":0,
	"previousMiningCycles":0,
	"paperclipsSpent":0,
	"miningEnabled":false,
	"miningSpeed":2000,
	"paperclipOutputDir":"/.paperclips/.paperclip-output/",
	"userChanged":false,
	"limerickHidden":false,
	"paperclipHidden":false,
	"miningStarted":null
};
module.exports = config;